version: 2

updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    ignore:
      # Ignore major updates as most major updates will need manual intervention
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "docstring-generator-vscode"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-minor"
          - "version-update:semver-major"
