[project]
name = "docstring-generator"
version = "2.1.2"
description = "Auto generate docstring from type-hints."
authors = [
    { name = "FelixTheC" },
]
readme = "README.md"
requires-python = ">=3.13"

# License metadata
license = { text = "Apache-2.0" }

classifiers=[
    "Environment :: Console",
    "Programming Language :: Python :: 3",
    "Topic :: Utilities",
    "Topic :: Software Development :: Documentation",
    "Typing :: Typed",
    "License :: OSI Approved :: Apache Software License",
]

dependencies = [
    "click == 8.4.2",
    "docstring-generator-ext>=2.0.9",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff==0.15.21",
    "fastapi==0.140.0",
    "sqlalchemy==2.0.51"
]

[tool.uv]
no-binary-package = ["docstring-generator-ext"]

[tool.uv.extra-build-variables]
docstring-generator-ext = { MACOSX_DEPLOYMENT_TARGET = "13.3", CXXFLAGS = "-std=c++20", CL = "/std:c++20" }

[project.urls]
Repository = "https://github.com/FelixTheC/docstring_generator"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

# --- TOOL CONFIGS ---
[tool.ruff]
line-length = 100
target-version = "py313"
src = ["src"]
exclude = ["tests"]

[project.scripts]
gendocs_new = "docstring_generator.new_gen_docs:main"

# Ensure non-code files like NOTICE are included in sdist/wheel
[tool.setuptools]
include-package-data = true

[tool.setuptools.data-files]
"doc" = ["NOTICE"]
